update

diff --git a/.github/workflows/submodule-sync-by-tag.yml b/.github/workflows/submodule-sync-by-tag.yml
--- a/.github/workflows/submodule-sync-by-tag.yml
+++ b/.github/workflows/submodule-sync-by-tag.yml
@@ -15,6 +15,7 @@ on:
       - closed
 
 env:
+  TAG_VALIDATION: '^v(\.\d+)+$'
   TARGET_BRANCH: develop
   SUBMODULE_DIR: themes/techblog
   NEW_BRANCH_BASE: design
@@ -44,6 +45,10 @@ jobs:
         if: ${{ github.event.inputs.targetTag }}
         run: |
           cd "${SUBMODULE_DIR}"
+          if ! echo "${{ github.event.inputs.targetTag }}" | grep -E "$TAG_VALIDATION"; then
+            echo "The target tag ${{ github.event.inputs.targetTag }} is invalid format."
+            exit 1
+          fi
           if git tag -l --sort -authordate | grep -x "${{ github.event.inputs.targetTag }}"; then
             exit 0
           else
@@ -56,7 +61,11 @@ jobs:
         run: |
           cd "${SUBMODULE_DIR}"
           LATEST_TAG="$(git tag -l --sort -authordate | head -n 1)"
-          echo "::set-output name=latestTag::$LATEST_TAG"
+          if ! echo "${LATEST_TAG}" | grep -E "$TAG_VALIDATION"; then
+            echo "The latest tag ${LATEST_TAG} is invalid format."
+            exit 1
+          fi
+          echo "::set-output name=latestTag::${LATEST_TAG}"
       - name: Download the Current Tag Artifact
         if: ${{ ! github.event.inputs.targetTag }}
         uses: actions/download-artifact@v3.0.0
@@ -68,7 +77,7 @@ jobs:
         if: ${{ ! github.event.inputs.targetTag }}
         run: |
           CURRENT_TAG="$(cat .artifact/currentTag.json | jq -r '.tag')"
-          echo "::set-output name=currentTag::$CURRENT_TAG"
+          echo "::set-output name=currentTag::${CURRENT_TAG}"
       - name: Detect Submodule Updates
         if: ${{ ! github.event.inputs.targetTag }}
         run: |
@@ -84,12 +93,12 @@ jobs:
           TARGET: ${{ github.event.inputs.targetTag }}
           LATEST: ${{ steps.stepLatestTag.outputs.latestTag }}
         run: |
-          if [ -n "$TARGET" ]; then
-            echo "::set-output name=processingTag::$TARGET"
+          if [ -n "${TARGET}" ]; then
+            echo "::set-output name=processingTag::${TARGET}"
             exit 0
           fi
-          if [ -n "$LATEST" ]; then
-            echo "::set-output name=processingTag::$LATEST"
+          if [ -n "${LATEST}" ]; then
+            echo "::set-output name=processingTag::${LATEST}"
             exit 0
           fi
           echo 'The processing tag cannot be defined.'
@@ -162,4 +171,9 @@ jobs:
     runs-on: ubuntu-latest
     if: ${{ github.event.pull_request }}
     steps:
-      - run: echo "nothing to do"
+      - run: |
+        echo "nothing to do"
+        echo "head ref"
+        echo ${{ github.head_ref }}
+        echo "base ref"
+        echo ${{ github.base_ref }}
